In [1]:
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [2]:
# Creating arrays with arange
arr = np.arange(10)
print(arr)

# Reshaping arrays
reshaped_arr = arr.reshape(2, 5)
print(reshaped_arr)


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [3]:
arr = np.array([1, 2, 3, 4, 5])

# Element-wise addition
arr = arr + 10
print(arr)

# Statistical operations
print(np.mean(arr))
print(np.std(arr))


[11 12 13 14 15]
13.0
1.4142135623730951


In [4]:
data = np.random.randn(1000)

# Calculating mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)
print(f"Mean: {mean}, Standard Deviation: {std_dev}")


Mean: -0.009487713158351046, Standard Deviation: 0.9749386350602405
